apiVersion: v1
kind: Pod
metadata:
  name: dcgmproftester-3g
spec:
  restartPolicy: OnFailure
  containers:
  - name: dcgmproftester11
    image: nvidia/samples:dcgmproftester-2.0.10-cuda11.0-ubuntu18.04
    args: ["--no-dcgm-validation", "-t 1004", "-d 240"]
    resources:
      limits:
         nvidia.com/mig-3g.20gb: 1
    securityContext:
      capabilities:
         add: ["SYS_ADMIN"]
  nodeSelector:  #optional
    nvidia.com/gpu.product: NVIDIA-A100-PCIE-40GB


