apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    nvidia.com/last-applied-hash: c606cade88a0173a
    openshift.io/scc: hostmount-anyuid
  creationTimestamp: "2022-08-17T09:17:50Z"
  generation: 1
  labels:
    app: nvidia-container-toolkit-daemonset
  name: nvidia-container-toolkit-daemonset
  namespace: gpu-operator
  ownerReferences:
  - apiVersion: nvidia.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: ClusterPolicy
    name: cluster-policy
    uid: 37655638-cd6e-426e-893f-f16108ef4222
  resourceVersion: "246748"
  uid: a099dc0f-458a-43a2-9f62-f6b7a792d818
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nvidia-container-toolkit-daemonset
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nvidia-container-toolkit-daemonset
    spec:
      containers:
      - args:
        - '[[ -f /run/nvidia/validations/host-driver-ready ]] && driver_root=/ ||
          driver_root=/run/nvidia/driver; export NVIDIA_DRIVER_ROOT=$driver_root;
          exec nvidia-toolkit /usr/local/nvidia'
        command:
        - bash
        - -c
        env:
        - name: RUNTIME_ARGS
          value: --socket /runtime/sock-dir/containerd.sock --config /runtime/config-dir/config.toml
        - name: RUNTIME
          value: containerd
        - name: CONTAINERD_RUNTIME_CLASS
          value: nvidia
        image: nvcr.io/nvidia/k8s/container-toolkit:v1.10.0-ubuntu20.04
        imagePullPolicy: IfNotPresent
        name: nvidia-container-toolkit-ctr
        resources: {}
        securityContext:
          privileged: true
          seLinuxOptions:
            level: s0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/nvidia
          mountPropagation: Bidirectional
          name: nvidia-run-path
        - mountPath: /usr/local/nvidia
          name: nvidia-local
        - mountPath: /usr/share/containers/oci/hooks.d
          name: crio-hooks
        - mountPath: /host
          mountPropagation: HostToContainer
          name: host-root
          readOnly: true
        - mountPath: /runtime/config-dir/
          name: containerd-config
        - mountPath: /runtime/sock-dir/
          name: containerd-socket
      dnsPolicy: ClusterFirst
      hostPID: true
      initContainers:
      - args:
        - nvidia-validator
        command:
        - sh
        - -c
        env:
        - name: WITH_WAIT
          value: "true"
        - name: COMPONENT
          value: driver
        image: nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.11.1
        imagePullPolicy: IfNotPresent
        name: driver-validation
        resources: {}
        securityContext:
          privileged: true
          seLinuxOptions:
            level: s0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/nvidia/driver
          mountPropagation: HostToContainer
          name: driver-install-path
        - mountPath: /run/nvidia/validations
          mountPropagation: Bidirectional
          name: run-nvidia-validations
        - mountPath: /host
          mountPropagation: HostToContainer
          name: host-root
          readOnly: true
      nodeSelector:
        nvidia.com/gpu.deploy.container-toolkit: "true"
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nvidia-container-toolkit
      serviceAccountName: nvidia-container-toolkit
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      volumes:
      - hostPath:
          path: /run/nvidia
          type: DirectoryOrCreate
        name: nvidia-run-path
      - hostPath:
          path: /run/nvidia/validations
          type: DirectoryOrCreate
        name: run-nvidia-validations
      - hostPath:
          path: /run/nvidia/driver
          type: ""
        name: driver-install-path
      - hostPath:
          path: /
          type: ""
        name: host-root
      - hostPath:
          path: /usr/local/nvidia
          type: ""
        name: nvidia-local
      - hostPath:
          path: /run/containers/oci/hooks.d
          type: ""
        name: crio-hooks
      - hostPath:
          path: /etc/containerd
          type: ""
        name: containerd-config
      - hostPath:
          path: /run/containerd
          type: ""
        name: containerd-socket
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
