apiVersion: v1
kind: Pod
metadata:
  name: tf-benchmarks-m6x2
spec:
  restartPolicy: Never
  containers:
    - name: tf-benchmarks-m6
      image: "nvcr.io/nvidia/tensorflow:20.08-tf2-py3"
      command: ["/bin/sh", "-c"]
      args: ["cd /workspace && git clone https://github.com/tensorflow/benchmarks/ && cd /workspace/benchmarks/scripts/tf_cnn_benchmarks && python tf_cnn_benchmarks.py --num_gpus=2 --batch_size=64 --model=resnet50 --use_fp16"]
      resources:
        limits:
          nvidia.com/gpu: 2
  nodeSelector:  #optional
    nvidia.com/gpu.product: Tesla-M6

